### ISSUE TITLE
Milestone 2: Summary of the Work Done by Each Team Member

### ISSUE THREAD

**Issue by araldortogul** [bounswe/bounswe2022group6#145]
For the report of the second milestone, the summary of the work done by each team member needs to be prepared in a tabular format until 20.05.2022.

Each member should write their own contributions and must provide related issues' URIs.

**Deadline:** 20.05.2022

Everyone can check the summary table and put a mark next to their name below after reviewing their summary.

Team Members:
- [x] Ali Kaan Biber
- [ ] Alp Eren İnceoğlu
- [x] Aral Dörtoğul
- [x] Artun Akdoğan
- [x] Berfin Şimşek
- [x] Beyza İrem Urhan
- [x] Hakan Balık
- [x] Hatice Erk
- [ ] Mustafa Berk Turgut
- [x] Bedirhan Pamukçuoğlu
- [x] Yasir Dikbaş
- [x] Yusuf Erdem Nacar

**Comment by LehabuL** [comment]
I finished my part but since there are still a little bit of work, I might update it later on.

**Comment by BPamukcuoglu** [comment]
I have written the summary of work carried out by me.

**Comment by artun-akdogan** [comment]
I have written the summary of work carried out by me in the report

**Comment by yusuferdemnacar** [comment]
I added a detailed list of my work to the report. Thanks.

**Comment by iremmer** [comment]
I also added my summary of work.
