### ISSUE TITLE
Implementing Login

### ISSUE THREAD

**Issue by yusuferdemnacar** [bounswe/bounswe2022group6#212]
Login functionality should be implemented. We will use the Django REST framework's TokenAuthenticaton.

* The login endpoint should return the user token as a response
* Future implementations of
  * [Adding information to an account](https://github.com/bounswe/bounswe2022group6/wiki/Requirements#1112-adding-information-to-a-account)
  * [Editing information on an account](https://github.com/bounswe/bounswe2022group6/wiki/Requirements#1113-editing-the-information-in-an-account)
  * [Removing information from an account](https://github.com/bounswe/bounswe2022group6/wiki/Requirements#1114-removing-information-from-an-account)
  * [Deleting an account](https://github.com/bounswe/bounswe2022group6/wiki/Requirements#1115-deleting-an-account)
  * [Logging out](https://github.com/bounswe/bounswe2022group6/wiki/Requirements#1116-logging-inlogging-out)

* Should make use of the token that was given to a user that logged in.

**Tasks**

- [x] Creating an API documentation
- [x] Implementing login functionality
- [x] Creating unit tests

**Deadline:** 28.10.2022

**Comment by yusuferdemnacar** [comment]
The login functionality is implemented.

I also wrote an API documentation for this endpoint in JSON format. You can easily use it in Postman. 

You can find the commits here;
* User model update - 34a448b91fd44adcb707f270da183a0f0a5b7188
* Login functionality implementation - 924ca56a668405df8b36b770187ced6e2ac05c2b
* API documentation - cfd441ca070a2e3e5df59465586d6211ccd25630

**Further work**
- [ ] Unit tests for the login endpoint should be created.

**Comment by yusuferdemnacar** [comment]
The unit tests for the login functionality are added. You can find the commit here, 8b6996a72dbf5320e48483bd937a5c6ab05e2aa5.
