### ISSUE TITLE
Implementing Logout

### ISSUE THREAD

**Issue by yusuferdemnacar** [bounswe/bounswe2022group6#220]
Logout functionality should be implemented using the Django REST framework's TokenAuthenticaton.

* Should make use of the token given to a user logged in.
   * A user that was not logged in cannot log out.

**Tasks**

- [x] Creating an API documentation
- [x] Implementing logout functionality
- [x] Creating unit tests

**Deadline:** 30.10.2022

**Comment by yusuferdemnacar** [comment]
The logout functionality is implemented.

I also wrote an API documentation for this endpoint in JSON format. You can easily use it in Postman. 

You can find the commits here;
* Logout functionality implementation - 04f8bae1128533d1d940b570e8aa66f01d894606
* API documentation - 40ed9d9b57f7f0f0f3abbce4af47c83cc773fe72
* Unit tests - 59cb0d086a66da42726f2eaff328e0023cd42426
