### ISSUE TITLE
Preparing Customer Milestone 1 Deliverables

### ISSUE THREAD

**Issue by araldortogul** [bounswe/bounswe2022group6#227]
Customer milestone 1 is drawing closer, and its deliverables should be prepared.

In addition to the code, a folder titled **CMPE451_Customer_Presentation_Milestone_1** must be created inside [deliverables](https://github.com/bounswe/bounswe2022group6/tree/master/deliverables) folder in the repository. All the deliverables should be committed to this directory.

This submission includes all the software artifacts related to the software development activities performed thus far. It includes all the code, requirements, designs, planning, and management artifacts.

**Format:** Markdown Document. All the report documents must be submitted as `.md` files.

### Deliverables

The following deliverables will be compiled into a single report.

- [x] Software Requirements Specification
- [x] Software Design (UML)
- [x] Scenarios and Mockups - #230
- [x] Project Plan - #201 
- [x] Individual Contribution Reports - #231
- [x] Customer Milestone 1 Group Review - #232 

### Deadline:
- All deliverables except Milestone Group Review: 01.11.2022 12:00
- Milestone Group Review: 04.11.2022  22:55

**Comment by LehabuL** [comment]
I initialized the file, added the topics and listed down individual report names in alphabetically sorted order with respect to surnames. You can find the file under deliverables folder [here](https://github.com/bounswe/bounswe2022group6/blob/master/deliverables/CMPE451_Customer_Presentation_Milestone_1.md).

**Comment by yusuferdemnacar** [comment]
Since most of these documents are separate tasks, I believe it would be beneficial to create separate issues for them to track more efficiently. Especially the ones that require step-by-step tracking.

I think it would be better to have separate issues for
* Scenarios and mockups
* Project plan
* Individual Contribution Reports
* Group Review Report

So I'm opening the non-existent ones and linking the existing ones.

**Comment by yusuferdemnacar** [comment]
> I initialized the file, added the topics and listed down individual report names in alphabetically sorted order with respect to surnames. You can find the file under deliverables folder [here](https://github.com/bounswe/bounswe2022group6/blob/master/deliverables/CMPE451_Customer_Presentation_Milestone_1.md).

Thanks. By the way, I noticed that we are supposed to create a folder with that name, not a file, just to let you know.

**Comment by LehabuL** [comment]
Last semester we have created a single file which consisted of all of the deliverables so I thought we would do the same for this one as well @yusuferdemnacar.

**Comment by yusuferdemnacar** [comment]
Well yeah, I also think that it looks kinda redundant

**Comment by yusuferdemnacar** [comment]
> Since most of these documents are separate tasks, I believe it would be beneficial to create separate issues for them to track more efficiently. Especially the ones that require step-by-step tracking.
> 
> So I'm opening the non-existent ones and linking the existing ones.

The issues
* #230
* #231

Have been created and

* #201

is linked.

**Comment by LehabuL** [comment]
I have added links for Requirements, UML Diagrams, Scenarios & Mockups and the Project Plan on the commit 5b9bcb000cddf5bcc036ca8c1a7cb20096aa4d2e

**Comment by araldortogul** [comment]
> I have added links for Requirements, UML Diagrams, Scenarios & Mockups and the Project Plan on the commit [5b9bcb0](https://github.com/bounswe/bounswe2022group6/commit/5b9bcb000cddf5bcc036ca8c1a7cb20096aa4d2e)

Thanks @LehabuL for the additions.

**Comment by araldortogul** [comment]
The report has been submitted, therefore. I am closing this issue.
