### ISSUE TITLE
Resolving Final Issues Regarding Deployment For Milestone I

### ISSUE THREAD

**Issue by yusuferdemnacar** [bounswe/bounswe2022group6#240]
Final deployment for the Milestone I demo should be done. The deployment will be to the AWS EC2 instance that we use as a team for the course.
The issues that came up or may come up should be resolved in the meeting for this task.

**Tasks**
- [x] Change URLs in the fronted code from localhost to the actual URL.
- [x] Allow all CORS headers for the server to respond to outside requests.
- [x] Deploy the application to the AWS EC2 instance after the changes above
- [x] Test the register, login, and logout functionalities on the deployed application.

**Deadline:** 31.10.2022 - 23.59

**Comment by artun-akdogan** [comment]
Requested tasks have been completed by @artun-akdogan, @LehabuL, and @yusuferdemnacar. Then, those changes have been tested and uploaded to AWS EC2 instance. Specified features are working properly.
