### ISSUE TITLE
Milestone Report 2 Individual Reports

### ISSUE THREAD

**Issue by LehabuL** [bounswe/bounswe2022group6#320]
As discussed in [Meeting 9](https://github.com/bounswe/bounswe2022group6/wiki/Meeting-%239-04.12.2022), each member should fill their Individual reports in [Milestone Report 2](https://github.com/bounswe/bounswe2022group6/blob/master/deliverables/CMPE451_Customer_Presentation_Milestone_2.md) which consist of the followings:

- Member: Info about myself (name, group), Subgroup if applicable (such as backend, frontend,
 android)
- Responsibilities: Overall description of the responsibilities that are assigned to me
- Main contributions: Overall description of my contributions to the project until Customer Milestone Presentation
   - Code related significant issues: My issues that contribute to the code base demonstrated
during the demo
   - Management related significant issues: My issues that contribute to the management of our
software project
   - Note that only the most-significant ones, we track all your issues separately.
- Pull requests: My pull requests
- Unit Tests: All unit tests that you have personally written for your project since the beginning of the project.
- Additional information: Further relevant information related to my contributions (optional)

Please put a check mark once you are done.

- [ ] [Artun Akdoğan](https://github.com/artun-akdogan)
- [x] [Hakan Balık](https://github.com/LehabuL)
- [x] [Ali Kaan Biber](https://github.com/Aliqaan)
- [x] [Yasir Dikbaş](https://github.com/yasirdikbas)
- [ ] [Aral Dörtoğul](https://github.com/araldortogul)
- [x] [Ihsan Mert Atalay](https://github.com/ihsanmertatalay)
- [ ] [Alp Eren İnceoğlu](https://github.com/aeren)
- [ ] [Yusuf Erdem Nacar](https://github.com/yusuferdemnacar)
- [ ] [Ramazan Bedirhan Pamukçuoğlu](https://github.com/BPamukcuoglu)
- [ ] [Berfin Şimşek](https://github.com/berfinsimsekk)
- [ ] [Mustafa Berk Turgut](https://github.com/mberkturgut)
- [ ] [Beyza İrem Urhan](https://github.com/iremmer)

**Deadline:** 09.12.2022

**Comment by LehabuL** [comment]
Since we have already sent the Milestone Report 2 I am closing the issue.
