### ISSUE TITLE
Preparing Individual Milestone Reports

### ISSUE THREAD

**Issue by araldortogul** [bounswe/bounswe2022group6#454]
Each team member must prepare their own individual milestone reports.

**Deadline:** 02.01.2023 23:59

Please put a tick next to your name when you finish preparing your individual milestone report.

Member:
- [x] Artun Akdoğan
- [x] İhsan Mert Atalay
- [x] Hakan Balık
- [x] Ali Kaan Biber
- [x] Yasir Dikbaş
- [x] Aral Dörtoğul
- [x] Alp Eren İnceoğlu
- [x] Yusuf Erdem Nacar
- [x] Bedirhan Pamukçuoğlu
- [x] Berfin Şimşek
- [ ] Mustafa Berk Turgut
- [x] Beyza İrem Urhan

You can find the details of the report below:

_While preparing your individual report, provide the necessary hyperlinks and references to your work on GitHub. The individual milestone report must include your personal contributions through the project. Provide this information in a manner that is consistent with software engineering concepts and references to your work. Such work includes all activities related to the development of software as well as the management of the development process._

1. **Member:** Info about myself (name, group), Subgroup if applicable (such as backend, frontend, android)
2. **Responsibilities:** Overall description of the responsibilities that are assigned to me
3. **Main Contributions:** Overall description of my contributions to the project until Customer Milestone Presentation
    - **Code related significant issues:** My issues that contribute to the code base demonstrated during the demo
    - **Management related significant issues:** My issues that contribute to the management of our software project
4. **Pull requests:** My pull requests
5. **Unit Tests:** All unit tests that you have personally written for your project since the beginning of the project.
6. **(Optional) Additional information:** Further relevant information related to my contributions
