### ISSUE TITLE
Milestone I Report: Summary of the work Done by Each Team Member

### ISSUE THREAD

**Issue by araldortogul** [bounswe/bounswe2022group6#86]
For the report of the first milestone, the summary of the work done by each team member until 15.04.2022 needs to be prepared in a tabular format.

**Deadline:** 15.04.2022, 22:00

Everyone can check the summary table and put a mark next to their name below after reviewing their summary.

Team Members:
- [x] Ali Kaan Biber
- [x] Alp Eren İnceoğlu
- [x] Aral Dörtoğul
- [x] Artun Akdoğan
- [x] Berfin Şimşek
- [x] Beyza İrem Urhan
- [x] Hakan Balık
- [x] Hatice Erk
- [x] Mustafa Berk Turgut
- [x] Bedirhan Pamukçuoğlu
- [x] Yasir Dikbaş
- [x] Yusuf Erdem Nacar

**Comment by yusuferdemnacar** [comment]
I filled my part for the work summary in the shared Google Doc document.

**Comment by mberkturgut** [comment]
I also have completed my part

**Comment by yasirdikbas** [comment]
My part is now complete.
