### ISSUE TITLE
Preparing the Report of Milestone 1

### ISSUE THREAD

**Issue by araldortogul** [bounswe/bounswe2022group6#87]
A milestone report that gathers the major deliverables related to the requirements, design, and plan of the project must be prepared.

The milestone report must include at least the following items:

- [x]  1. Title page, with course names, group number and contributors.
- [x]  2. Table of Contents with page numbers
- [x]  3. Executive Summary: Summary of the project status and any changes that are planned for moving forward.
- [x]  4. List and status of deliverables.
- [x]  5. Evaluation of the status of deliverables and its impact on the project plan.
- [x]  6. Evaluation of tools and processes that have been used to manage the project.
- [x]  7. A summary of work done by each team member (in tabular format).

**Comment by yusuferdemnacar** [comment]
I have written parts 3 and 6 in the shared Google Doc document and reported the work under #83.

**Comment by LehabuL** [comment]
I handed over the creation of title page to @iremmer and will be creating the table of contents as soon as the draft version of the Milestone Report is available.

**Comment by mberkturgut** [comment]
Parts 4 & 5 are completed by @yasirdikbas and me.
